#!/bin/bash

case $1 in 
	push)
		git add .
		git add -A .
		git commit -m "$2"
		git push origin master
	;;
	save)
		git commit -am "$2"
	;;
	*)
		echo "Usage: ./forest [ { push | save } [comment] ]"
		exit 1
	;;
esac
exit 0
